from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path

from kanbanlan.config import CONFIG_FILENAME, Config

START_MARKER = "<!-- kanbanlan:start -->"
END_MARKER = "<!-- kanbanlan:end -->"
MANAGED_FILE_MARKER = "<!-- Generated by kanbanlan; run `kanbanlan init` to refresh. -->"

STATUS_LABELS = {
    "status:intake": ("D4C5F9", "Captured but not ready"),
    "status:ready": ("0E8A16", "Scoped and unblocked"),
    "status:in-progress": ("FBCA04", "Claimed by one active session"),
    "status:blocked": ("D73A4A", "Waiting on a dependency or decision"),
    "status:review": ("1D76DB", "Pull request is open"),
}
PRIORITY_LABELS = {
    "priority:p0": ("B60205", "Incident or release blocker"),
    "priority:p1": ("D93F0B", "Next up"),
    "priority:p2": ("FBCA04", "Planned"),
    "priority:p3": ("C5DEF5", "Later"),
}


@dataclass(frozen=True)
class WriteResult:
    path: Path
    action: str


def scaffold_repository(root: Path, config: Config, *, force: bool = False) -> list[WriteResult]:
    results = [
        _write(root / CONFIG_FILENAME, config.to_toml(), force=True),
        _write_managed_file(
            root / ".github" / "ISSUE_TEMPLATE" / "work-request.yml",
            issue_template(),
            force=force,
        ),
        _write_managed_file(
            root / ".github" / "pull_request_template.md",
            pull_request_template(config),
            force=force,
        ),
        _write_managed_file(
            root / "docs" / "workflow" / "kanbanlan.md",
            workflow_doc(config),
            force=force,
        ),
    ]
    block = agent_instructions(config)
    results.append(_upsert_section(root / "AGENTS.md", "# AGENTS.md", block))
    results.append(_upsert_section(root / "CLAUDE.md", "# CLAUDE.md", block))
    results.append(_append_gitignore(root / ".gitignore"))
    return results


def _write(path: Path, content: str, *, force: bool) -> WriteResult:
    path.parent.mkdir(parents=True, exist_ok=True)
    if path.exists() and not force and path.read_text(encoding="utf-8") != content:
        return WriteResult(path, "skipped (custom file)")
    action = "updated" if path.exists() else "created"
    path.write_text(content, encoding="utf-8")
    return WriteResult(path, action)


def _write_managed_file(path: Path, content: str, *, force: bool) -> WriteResult:
    rendered = f"{MANAGED_FILE_MARKER}\n{content.lstrip()}"
    if path.exists():
        existing = path.read_text(encoding="utf-8")
        if MANAGED_FILE_MARKER not in existing and not force:
            return WriteResult(path, "skipped (custom file)")
    return _write(path, rendered, force=True)


def _upsert_section(path: Path, default_heading: str, body: str) -> WriteResult:
    path.parent.mkdir(parents=True, exist_ok=True)
    if path.exists():
        existing = path.read_text(encoding="utf-8")
    else:
        existing = f"{default_heading}\n"
    managed = f"{START_MARKER}\n{body.strip()}\n{END_MARKER}"
    if START_MARKER in existing and END_MARKER in existing:
        before, remainder = existing.split(START_MARKER, 1)
        _, after = remainder.split(END_MARKER, 1)
        rendered = f"{before}{managed}{after}"
        action = "updated"
    else:
        rendered = f"{existing.rstrip()}\n\n{managed}\n"
        action = "updated" if path.exists() else "created"
    path.write_text(rendered, encoding="utf-8")
    return WriteResult(path, action)


def _append_gitignore(path: Path) -> WriteResult:
    entry = "/.cache/kanbanlan/"
    existing = path.read_text(encoding="utf-8") if path.exists() else ""
    if entry in existing.splitlines():
        return WriteResult(path, "unchanged")
    prefix = existing.rstrip()
    rendered = (
        f"{prefix}\n\n# Local Kanbanlan coordination cache\n{entry}\n" if prefix else f"{entry}\n"
    )
    path.write_text(rendered, encoding="utf-8")
    return WriteResult(path, "updated" if existing else "created")


def issue_template() -> str:
    return """name: Work request
description: Capture one independently reviewable outcome.
title: "[Request] "
labels:
  - "status:intake"
body:
  - type: markdown
    attributes:
      value: |
        One card is one outcome and, while active, belongs to one session.

  - type: textarea
    id: outcome
    attributes:
      label: Outcome
      description: Describe the user-visible or operational result.
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Context
      description: Include relevant evidence, decisions, and links.
    validations:
      required: true

  - type: textarea
    id: acceptance
    attributes:
      label: Acceptance criteria
      placeholder: "- [ ] ..."
    validations:
      required: true

  - type: textarea
    id: boundaries
    attributes:
      label: Scope boundaries
      description: State what is in and out of scope.
    validations:
      required: true

  - type: textarea
    id: touchpoints
    attributes:
      label: Likely touchpoints
      description: Name behaviors, contracts, migrations, shared UI, docs, and likely paths.
    validations:
      required: true

  - type: textarea
    id: dependencies
    attributes:
      label: Dependencies and overlap
      description: Link cards or PRs that block, precede, or may collide with this request.
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      options:
        - P0 - incident or release blocker
        - P1 - next up
        - P2 - planned
        - P3 - later
      default: 2
    validations:
      required: true

  - type: textarea
    id: verification
    attributes:
      label: Verification
      description: Name the automated and manual evidence expected before merge.
    validations:
      required: true
"""


def pull_request_template(config: Config) -> str:
    staging = config.stage_branch or config.default_branch
    return f"""## Request card

Closes #

## Outcome

<!-- Describe the result delivered by this PR. -->

## Scope and coordination

- [ ] This PR contains only the linked card's outcome and necessary supporting work.
- [ ] I rechecked active cards and pull requests for overlap.
- Dependencies, blockers, or shared touchpoints: <!-- None, or links. -->

## Verification

<!-- List commands run and manual evidence collected. -->

- [ ] Relevant automated checks pass.
- [ ] Manual behavior was verified where applicable.
- [ ] Documentation and screenshots are updated where applicable.

## Staging review

- Target branch/environment: `{staging}`
- [ ] Prepared for or verified on staging before production promotion.
- Evidence or next step: <!-- URL, workflow, reviewer, or pending step. -->

## Risk and rollback

<!-- Note migrations, shared contracts, rollout concerns, and a safe rollback. -->
"""


def agent_instructions(config: Config) -> str:
    owner_segment = "orgs" if config.project_owner_type == "organization" else "users"
    project_url = (
        f"https://github.com/{owner_segment}/{config.project_owner}/projects/"
        f"{config.project_number}"
    )
    return f"""## Request Coordination Workflow

GitHub Issues are canonical request cards. [{config.project_owner} Project
{config.project_number}]({project_url}) is their Kanban view. Follow
`docs/workflow/kanbanlan.md`.

- At session start run `kanbanlan ensure`. Before mutations run
  `kanbanlan reconcile` and inspect all open cards and pull requests for
  semantic overlap. If live coordination state is unavailable, do not start
  potentially overlapping implementation.
- Status questions are read-only. “Remember this” creates an Inbox card.
  “Let's work on this” authorizes a live overlap check and one claim.
- Create or reuse one issue per independently reviewable outcome. One session
  may own exactly one `status:in-progress` card, and one card may have exactly
  one active session. Claim with `kanbanlan claim <issue> --touchpoints ...`.
- Use a dedicated issue branch and worktree. Block semantic conflicts even when
  filenames differ. Do not expand a claimed card into another useful outcome.
- A pull request closes its issue and moves it to In review. Ownership lasts
  until merge, explicit release, or handoff. Project Done means delivered to
  `{config.stage_branch}`; production readiness still requires staging review.
"""


def workflow_doc(config: Config) -> str:
    return f"""# Request coordination with Kanbanlan

This repository uses Kanbanlan to coordinate GitHub Issues on Project
{config.project_number}, owned by `{config.project_owner}`. The repository
binding is `{config.repository}`.

## Daily commands

```sh
kanbanlan ensure
kanbanlan next
kanbanlan status
kanbanlan reconcile
```

`ensure` refreshes a private local cache shared by Git worktrees.
`reconcile` reports drift between issue labels, active claims, pull requests,
and the Project Status field. Use `kanbanlan reconcile --apply` only after
reviewing the plan.

## States

| Issue label | Project Status | Meaning |
| --- | --- | --- |
| `status:intake` | Inbox | Captured, not ready. |
| `status:ready` | Ready | Scoped and unblocked. |
| `status:in-progress` | In progress | Claimed by one session. |
| `status:blocked` | Blocked | Waiting on a dependency or decision. |
| `status:review` | In review | A linked pull request is open. |
| closed issue | Done | Delivered to the staging branch. |

Priority labels are `priority:p0` through `priority:p3`.

## Ownership

```sh
kanbanlan claim 123 --touchpoints "auth contract; src/auth; migrations"
kanbanlan release 123 --reason "Waiting for API decision"
kanbanlan review 123
```

The earliest unreleased CLAIM comment owns the card. Claims do not expire
automatically. Check the issue, branch, worktree, and PR before asking to take
over stale work.

## Delivery

Pull requests target `{config.default_branch}` and use `Closes #<issue>`.
Merging moves the card to Done. Done means delivered to
`{config.stage_branch}`, not production-ready. Production promotion remains a
separate review after staging verification.
"""
