from __future__ import annotations

import json
from dataclasses import dataclass
from pathlib import Path

from kanbanlan.config import CONFIG_FILENAME, Config

START_MARKER = "<!-- kanbanlan:start -->"
END_MARKER = "<!-- kanbanlan:end -->"
MANAGED_FILE_MARKER = "<!-- Generated by kanbanlan; run `kanbanlan init` to refresh. -->"
YAML_MANAGED_FILE_MARKER = "# Generated by kanbanlan; run `kanbanlan init` to refresh."

STATUS_LABELS = {
    "status:intake": ("D4C5F9", "Captured but not ready"),
    "status:ready": ("0E8A16", "Scoped and unblocked"),
    "status:in-progress": ("FBCA04", "Claimed by one active session"),
    "status:blocked": ("D73A4A", "Waiting on a dependency or decision"),
    "status:review": ("1D76DB", "Pull request is open"),
}
PRIORITY_LABELS = {
    "priority:p0": ("B60205", "Incident or release blocker"),
    "priority:p1": ("D93F0B", "Next up"),
    "priority:p2": ("FBCA04", "Planned"),
    "priority:p3": ("C5DEF5", "Later"),
}


@dataclass(frozen=True)
class WriteResult:
    path: Path
    action: str


def scaffold_repository(root: Path, config: Config, *, force: bool = False) -> list[WriteResult]:
    results = [
        _write(root / CONFIG_FILENAME, config.to_toml(), force=True),
        _write_managed_file(
            root / ".github" / "ISSUE_TEMPLATE" / "work-request.yml",
            issue_template(),
            force=force,
            marker=YAML_MANAGED_FILE_MARKER,
        ),
        _write_managed_file(
            root / ".github" / "pull_request_template.md",
            pull_request_template(config),
            force=force,
        ),
        _write_managed_file(
            root / "docs" / "workflow" / "kanbanlan.md",
            workflow_doc(config),
            force=force,
        ),
    ]
    block = agent_instructions(config)
    results.append(_upsert_section(root / "AGENTS.md", "# AGENTS.md", block))
    results.append(_upsert_section(root / "CLAUDE.md", "# CLAUDE.md", block))
    if config.session_tracking:
        for relative_path, content in session_tracking_hooks().items():
            results.append(_write(root / relative_path, content, force=force))
    results.append(_append_gitignore(root / ".gitignore"))
    return results


def session_tracking_hooks() -> dict[Path, str]:
    def session_start(harness: str) -> str:
        return (
            json.dumps(
                {
                    "hooks": {
                        "SessionStart": [
                            {
                                "matcher": "startup|resume|clear|compact",
                                "hooks": [
                                    {
                                        "type": "command",
                                        "command": f"kanbanlan session-hook --agent {harness}",
                                        "timeout": 5,
                                    }
                                ],
                            }
                        ]
                    }
                },
                indent=2,
            )
            + "\n"
        )

    agy = (
        json.dumps(
            {
                "kanbanlan-session-tracking": {
                    "PreInvocation": [
                        {
                            "type": "command",
                            "command": "kanbanlan session-hook --agent agy",
                            "timeout": 5,
                        }
                    ]
                }
            },
            indent=2,
        )
        + "\n"
    )
    return {
        Path(".codex/hooks.json"): session_start("codex"),
        Path(".claude/settings.json"): session_start("claude"),
        Path(".grok/hooks/kanbanlan.json"): session_start("grok"),
        Path(".agents/hooks.json"): agy,
    }


def _write(path: Path, content: str, *, force: bool) -> WriteResult:
    path.parent.mkdir(parents=True, exist_ok=True)
    exists = path.exists()
    existing = path.read_text(encoding="utf-8") if exists else None
    if existing == content:
        return WriteResult(path, "unchanged")
    if exists and not force:
        return WriteResult(path, "skipped (custom file)")
    action = "updated" if exists else "created"
    path.write_text(content, encoding="utf-8")
    return WriteResult(path, action)


def _write_managed_file(
    path: Path,
    content: str,
    *,
    force: bool,
    marker: str = MANAGED_FILE_MARKER,
) -> WriteResult:
    rendered = f"{marker}\n{content.lstrip()}"
    if path.exists():
        existing = path.read_text(encoding="utf-8")
        managed_markers = (MANAGED_FILE_MARKER, YAML_MANAGED_FILE_MARKER)
        if not any(value in existing for value in managed_markers) and not force:
            return WriteResult(path, "skipped (custom file)")
    return _write(path, rendered, force=True)


def _upsert_section(path: Path, default_heading: str, body: str) -> WriteResult:
    path.parent.mkdir(parents=True, exist_ok=True)
    if path.exists():
        existing = path.read_text(encoding="utf-8")
    else:
        existing = f"{default_heading}\n"
    managed = f"{START_MARKER}\n{body.strip()}\n{END_MARKER}"
    if START_MARKER in existing and END_MARKER in existing:
        before, remainder = existing.split(START_MARKER, 1)
        _, after = remainder.split(END_MARKER, 1)
        rendered = f"{before}{managed}{after}"
        action = "updated"
    else:
        rendered = f"{existing.rstrip()}\n\n{managed}\n"
        action = "updated" if path.exists() else "created"
    if rendered == existing:
        return WriteResult(path, "unchanged")
    path.write_text(rendered, encoding="utf-8")
    return WriteResult(path, action)


def _append_gitignore(path: Path) -> WriteResult:
    entries = ("/.cache/kanbanlan/", "/.worktrees/")
    legacy_heading = "# Local Kanbanlan coordination cache"
    heading = "# Local Kanbanlan coordination state"
    existing = path.read_text(encoding="utf-8") if path.exists() else ""
    lines = [heading if line == legacy_heading else line for line in existing.splitlines()]
    normalized = "\n".join(lines) + ("\n" if existing.endswith("\n") and lines else "")
    present = set(lines)
    missing = [entry for entry in entries if entry not in present]
    if not missing and normalized == existing:
        return WriteResult(path, "unchanged")
    prefix = normalized.rstrip()
    if missing:
        separator = "\n" if any(entry in present for entry in entries) else "\n\n"
        managed_heading = "" if heading in present else f"{heading}\n"
        addition = managed_heading + "\n".join(missing)
        rendered = f"{prefix}{separator if prefix else ''}{addition}\n"
    else:
        rendered = normalized
    path.write_text(rendered, encoding="utf-8")
    return WriteResult(path, "updated" if existing else "created")


def issue_template() -> str:
    return """name: Work request
description: Capture one independently reviewable outcome.
title: "[Request] "
labels:
  - "status:intake"
body:
  - type: markdown
    attributes:
      value: |
        One card is one outcome and, while active, belongs to one session.
        `kanbanlan reconcile --apply` assigns its portable Kanbanlan ID.

  - type: textarea
    id: outcome
    attributes:
      label: Outcome
      description: Describe the user-visible or operational result.
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Context
      description: Include relevant evidence, decisions, and links.
    validations:
      required: true

  - type: textarea
    id: acceptance
    attributes:
      label: Acceptance criteria
      placeholder: "- [ ] ..."
    validations:
      required: true

  - type: textarea
    id: boundaries
    attributes:
      label: Scope boundaries
      description: State what is in and out of scope.
    validations:
      required: true

  - type: textarea
    id: touchpoints
    attributes:
      label: Likely touchpoints
      description: Name behaviors, contracts, migrations, shared UI, docs, and likely paths.
    validations:
      required: true

  - type: textarea
    id: dependencies
    attributes:
      label: Dependencies and overlap
      description: Link cards or PRs that block, precede, or may collide with this request.
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      options:
        - P0 - incident or release blocker
        - P1 - next up
        - P2 - planned
        - P3 - later
      default: 2
    validations:
      required: true

  - type: textarea
    id: verification
    attributes:
      label: Verification
      description: Name the automated and manual evidence expected before merge.
    validations:
      required: true
"""


def pull_request_template(config: Config) -> str:
    staging = config.stage_branch or config.default_branch
    return f"""## Request card

Kanbanlan: KBL-

Closes #

## Outcome

<!-- Describe the result delivered by this PR. -->

## Scope and coordination

- [ ] This PR contains only the linked card's outcome and necessary supporting work.
- [ ] I rechecked active cards and pull requests for overlap.
- Dependencies, blockers, or shared touchpoints: <!-- None, or links. -->

## Verification

<!-- List commands run and manual evidence collected. -->

- [ ] Relevant automated checks pass.
- [ ] Manual behavior was verified where applicable.
- [ ] Documentation and screenshots are updated where applicable.
- [ ] `docs/kanbanlan/requests/<Kanbanlan ID>.md` records durable decisions and evidence.

## Staging review

- Target branch/environment: `{staging}`
- [ ] Prepared for or verified on staging before production promotion.
- Evidence or next step: <!-- URL, workflow, reviewer, or pending step. -->

## Risk and rollback

<!-- Note migrations, shared contracts, rollout concerns, and a safe rollback. -->
"""


def agent_instructions(config: Config) -> str:
    owner_segment = "orgs" if config.project_owner_type == "organization" else "users"
    project_url = (
        f"https://github.com/{owner_segment}/{config.project_owner}/projects/"
        f"{config.project_number}"
    )
    tracking = ""
    if config.session_tracking:
        tracking = """\
- Provider-native session tracking is enabled. Keep the generated agent hook
  active, and let lifecycle commands auto-detect the current agent session. Use
  `--actor-session HARNESS:SESSION_ID` only when automatic context is unavailable.
"""
    return f"""## Request Coordination Workflow

The canonical kanban home is `{config.canonical_home}`. GitHub Issues currently
store canonical requests, and [{config.project_owner} Project
{config.project_number}]({project_url}) is their projection. Repository policy
and durable delivery records remain versioned here. Follow
`docs/workflow/kanbanlan.md`.

- At session start run `kanbanlan ensure`. Before mutations run
  `kanbanlan reconcile` and inspect all open cards and pull requests for
  semantic overlap. When this repository shares its Project with other
  repositories, run `kanbanlan overlap` so the check covers them too. If live
  coordination state is unavailable, do not start potentially overlapping
  implementation.
- Status questions are read-only. “Remember this” creates an Inbox card.
  “Let's work on this” authorizes a live overlap check and one claim.
- Create or reuse one request per independently reviewable outcome. Each request
  has a provider-independent Kanbanlan ID. One session
  may own exactly one `status:in-progress` card, and one card may have exactly
  one active session. Claim with
  `kanbanlan claim <kanbanlan-id-or-provider-ref> --touchpoints ...`.
- Use a dedicated request branch and worktree. Block semantic conflicts even when
  filenames differ. Do not expand a claimed card into another useful outcome.
{tracking}- Run `kanbanlan record <kanbanlan-id-or-provider-ref>` in the implementation
  worktree and complete its durable decisions, verification, and delivered result.
- A pull request closes its issue and moves it to In review. Ownership lasts
  until merge, explicit release, close, or handoff. A request that ends without
  a merge is closed with
  `kanbanlan close <kanbanlan-id-or-provider-ref> --reason ...`, adding
  `--not-planned` when it will not be built. Project Done means delivered to
  `{config.stage_branch}`; production readiness still requires staging review.
"""


def workflow_doc(config: Config) -> str:
    return f"""# Request coordination with Kanbanlan

This repository uses `{config.canonical_home}` as its canonical kanban home.
GitHub Issues currently store requests, and Project {config.project_number},
owned by `{config.project_owner}`, is their board projection. The repository
binding is `{config.repository}`.

Each request has an immutable `KBL-...` Kanbanlan ID. Provider references such
as GitHub `#123` are aliases; lifecycle commands accept either form. The live
kanban home owns volatile queue and claim state. Workflow policy and completed
delivery evidence remain versioned in this repository.

## Daily commands

```sh
kanbanlan ensure
kanbanlan next
kanbanlan status
kanbanlan reconcile
kanbanlan --json next
```

`ensure` refreshes a private local cache shared by Git worktrees.
`reconcile` reports drift between request status, identity, active claims, pull
requests, and projections. It also reports requests that need a Kanbanlan ID.
Use `kanbanlan reconcile --apply` only after reviewing the plan. `--json`
provides stable structured output for agents without requiring an MCP server.

## Repository scope and Project scope

One GitHub Project can serve several repositories. Kanbanlan reads it at two
scopes, and the difference is visible in stable JSON as `source.scope`.

| Scope | Value | What it contains |
| --- | --- | --- |
| Repository | `repository` | Only content owned by `{config.repository}`. |
| Project | `project` | Every repository the Project already references. |

Repository scope is the default and the only scope lifecycle commands use.
`next`, `capture`, `claim`, `release`, `review`, `close`, `handoff`, `cleanup`,
and ordinary
`reconcile` stay repository-local, so a shared Project never hands this
repository another repository's work. Queue selection (`ready_cards` and
`next_ready`) stays repository-local even in project scope.

Project scope is read-only and always live; it never writes the shared cache.

```sh
kanbanlan overlap                 # open cards and pull requests Project-wide
kanbanlan status --project        # board counts per repository
kanbanlan --json snapshot --project
```

Project-scoped reads are bounded to repositories the Project already
references. They never enumerate repositories owned by the account. A peer
repository that cannot be read is reported in
`source.unavailable_repositories` rather than failing the read.

Every issue and pull request carries `repository` and a repository-qualified
`provider_ref` such as `github:{config.repository}#123`, so identically
numbered content in different repositories never collides. `display_id` stays
short (`#123`) for this repository and is qualified (`owner/repo#123`) for a
peer. A bare number is always a local reference: `kanbanlan record 123`
resolves in `{config.repository}` only, and a peer request needs its Kanbanlan
ID or a qualified reference.

## Cross-repository delivery

A request here can be delivered by a pull request in a peer repository. Two
references are explicit enough to cross that boundary:

- a repository-qualified closing reference, such as
  `Closes {config.repository}#123`; or
- the request's exact Kanbanlan ID declared in the pull request body, which the
  generated pull request template already asks for.

A bare `Closes #123` is only ever read inside the pull request's own
repository, so it can never reach a peer request by accident.

Each entry in `linked_open_pull_requests` reports `repository`, a qualified
`provider_ref`, and `linked_by`, which lists the routes that justified the link
(`closing_reference`, `kanbanlan_id`, or both). `kanbanlan review` accepts a
qualifying open cross-repository pull request and keeps the responsible claim.

Open pull requests are discovered across the repositories linked to the Project
or already carrying Project items, never across the account. In repository
scope a peer pull request is reported only while it delivers a request in
`{config.repository}`.

Ambiguity is reported rather than guessed. A pull request that names several
Kanbanlan IDs without declaring one, or that declares an ID carried by more
than one request, is listed in `linkage_problems` and linked to nothing.
`reconcile`, `overlap`, and `review` all surface those entries. Declaring one
ID on the `Kanbanlan:` line keeps a passing mention of another request
harmless.

## Capturing into another repository

A client-level Project can hold requests owned by several repositories. The
request belongs in the repository whose code will change, because that is the
repository whose queue must offer it and whose branch will deliver it.

```sh
kanbanlan capture "Add the HSA/FSA page" --repository OWNER/REPO
```

`capture` defaults to `{config.repository}` and never infers a destination from
the title or body. A target is only ever this repository or one you name.

Before any request is created, the target is validated and prepared: it must
parse as `OWNER/REPO` (a URL is accepted only on `{config.hostname}`), be
accessible, and be linked to the configured Project, and the workflow status
and priority labels are provisioned there. A target that cannot be reached or
linked fails while nothing has been created.

The new request keeps one Kanbanlan ID, joins the configured Project, and
reaches Inbox in the repository that owns it. Success output reports the
repository, the Kanbanlan ID, the qualified provider reference, and the
canonical URL.

If something fails after the request exists, the error names the exact created
URL and the repair to run. Do not run `capture` again: a second run creates a
second request with a new identity. Run `kanbanlan reconcile --apply` in the
repository that owns the request instead.

## Moving a request that landed in the wrong repository

A request that already exists moves with `rehome`, which preserves its
Kanbanlan ID, its discussion, and its Project state. Recreating it elsewhere
would fragment its history and break the portable identity.

```sh
kanbanlan rehome KBL-... --repository OWNER/REPO           # plan only
kanbanlan rehome KBL-... --repository OWNER/REPO --apply   # perform the move
```

The plan is the default and changes nothing. It reports what transfers, what
the target still needs, what GitHub will drop (a milestone, and any label the
target does not have), and anything that blocks the move.

A move is refused while the request has an active claim or a linked open pull
request, when it is closed, or when the destination is where it already lives.
Release the claim, or merge or close the pull request, and then move it. Only
same-host moves to the configured Project are supported; anything else fails
before a single mutation.

This moves the canonical request, not its implementation. Branches, worktrees,
commits, and pull requests stay where they are, and the request receives a new
issue number in its new repository. Look it up by its Kanbanlan ID, which never
changes.

If the transfer succeeds but reconciling the Project state fails, the error
names the new canonical URL and a retryable repair. Rerunning `rehome` finishes
the move; it never creates a replacement request.

## States

| Issue label | Project Status | Meaning |
| --- | --- | --- |
| `status:intake` | Inbox | Captured, not ready. |
| `status:ready` | Ready | Scoped and unblocked. |
| `status:in-progress` | In progress | Claimed by one session. |
| `status:blocked` | Blocked | Waiting on a dependency or decision. |
| `status:review` | In review | A linked pull request is open. |
| closed issue | Done | Delivered to the staging branch, or closed as not planned. |

Priority labels are `priority:p0` through `priority:p3`.

## Ownership

```sh
kanbanlan claim KBL-... --touchpoints "auth contract; src/auth; migrations"
kanbanlan release KBL-... --reason "Waiting for API decision"
kanbanlan review KBL-...
```

The earliest unreleased CLAIM comment owns the card. Claims do not expire
automatically. Check the canonical request, branch, worktree, and PR before
asking to take over stale work.

`claim` creates a worktree per request; `cleanup` is what removes them again:

```sh
kanbanlan cleanup                 # report what is safe to remove
kanbanlan cleanup --apply
```

It removes a worktree only when its request has no active claim, and it links a
worktree to its request through the Kanbanlan ID in the branch or directory name
that `claim` writes. It never touches the primary worktree, the worktree the
command runs in, a locked worktree, or one it cannot link to a request. A tree
with uncommitted changes or with commits the default branch does not have is
reported and kept; `--force` removes it anyway, and an unmerged branch always
outlives its worktree so the commits stay recoverable. The local branch is
deleted only when it is fully merged.

## Optional agent session tracking

Provider-native session attribution is disabled by default. On an existing
configuration, `kanbanlan init --session-tracking` enables it in place while
preserving the repository and Project binding. Disable it with
`kanbanlan init --no-session-tracking`; installed hook files remain inert and
are not deleted. Use `kanbanlan init --reconfigure` only to intentionally rerun
full Project setup. The repository configuration is:

```toml
[session_tracking]
enabled = true
```

`KANBANLAN_SESSION_TRACKING=true` or `false` overrides the repository setting
for one process. When enabled, Kanbanlan checks `--actor-session`, then
`KANBANLAN_AGENT_SESSION=HARNESS:SESSION_ID`, then the paired
`KANBANLAN_AGENT` and `KANBANLAN_SESSION_ID` variables, provider-native
variables, and finally fresh context registered by the generated agent hooks.
If no trustworthy ID is available, activity is recorded as unavailable rather
than being presented as resumable.

```sh
kanbanlan triage KBL-...
kanbanlan sessions KBL-...
kanbanlan resume KBL-...                 # print the native resume command
kanbanlan resume KBL-... --action claim --run
```

Supported resume adapters are Codex, Claude Code, Grok Build, and Google
Antigravity AGY. Session entries display as `<session-id> · <harness>`. Native
IDs are written to canonical request comments when tracking is enabled, so
enable it only where that visibility is acceptable. Local sessions still
require their original transcript store and account; an ID cannot recreate a
deleted or non-persisted transcript.
Claim and handoff history distinguishes the session that performed the action
from the session responsible for the resulting work. Resume follows the
responsible session, so a handoff targets its recipient.

## Durable request records

After claiming a request, create its repository record:

```sh
kanbanlan record KBL-...
```

This creates `docs/kanbanlan/requests/KBL-....md` once and never overwrites
manual edits. Record durable decisions, verification evidence, and the delivered
result there. Do not commit routine status movements or claim heartbeats.

## Delivery

Pull requests target `{config.default_branch}`, carry `Kanbanlan: KBL-...`,
and use `Closes #<issue>` while GitHub is canonical. Merging moves the card to
Done. Done means delivered to
`{config.stage_branch}`, not production-ready. Production promotion remains a
separate review after staging verification.

A request that ends without a merge is closed directly:

```sh
kanbanlan close KBL-... --reason "Delivered by <what shipped it>"
kanbanlan close KBL-... --reason "Duplicate of KBL-..." --not-planned
```

`close` releases any active claim, closes the canonical request as completed or
not planned, and settles the projection at Done. It refuses while a linked pull
request is still open, because merging that pull request is the closing path;
`--force` overrides the refusal when the pull request will never merge.

Successful live setup can register the repository with the optional user-scoped
worker. Manage it with `kanbanlan worker status`, `enable`, `disable`, `start`,
and `stop`; see `docs/workflow/worker.md` for macOS LaunchAgent and Linux
systemd user-service examples. The worker deduplicates worktrees, preserves
last-good snapshots, uses bounded retry/backoff, and never stores GitHub tokens.
"""
